spring:
  datasource:
    url: jdbc:postgresql://${ONLINE_VAR_HOST_NAME}/${ONLINE_VAR_DB_NAME}
    password: ${ONLINE_VAR_PASSWORD}
    username: ${ONLINE_VAR_USER_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  api:
    version: 0.4.0

  sprindoc:
    swagger-ui:
      path: /swagger-ui.html